### ISSUE TITLE
Compose playlist JS2 Week 4

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/JavaScript-Core-2-Coursework-Week4#189]
Proposed topics:
- scope
- call stack
- sync vs async
- `setTimeout` and `setInterval`

Link to proposed playlist 👉 https://www.youtube.com/playlist?list=PLozA7cloMbPiZf72Nv9xHNa22aGy8Nv1s

**Comment by Dedekind561** [comment]
@ewintram Thankyou for helping out with this! This is already a massive time saver! ⌛ 🙏

**Comment by ewintram** [comment]
hi @Dedekind561 please can you give me edit access to the playlist, OR add these videos?
scope (up to 12:20) - https://www.youtube.com/watch?v=ky2mNs4kGh8
callstack - https://www.youtube.com/watch?v=W8AeMrVtFLY
callstack (stretch, watch the video and use this site to explore the callstack and event loop in more detail) - http://latentflip.com/loupe/

**Comment by Dedekind561** [comment]
Cheers - just added those. But I'll also grant you access going forwards in case you want to tweak the playlists in the future. Will let you know when you're in
